services:
  backend:
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --workers 2 --proxy-headers --forwarded-allow-ips=*

  frontend:
    image: node:20-alpine
    container_name: nodo_frontend_dev
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules # Aislamiento estricto de binarios entre host y contenedor
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000/api
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 5173"
    networks:
      - nodo_network