"""Add plan_id to Tenant

Revision ID: 04683d9beeee
Revises: a1d310dc68bb
Create Date: 2026-05-07 03:11:51.739473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04683d9beeee'
down_revision: Union[str, Sequence[str], None] = 'a1d310dc68bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('plan_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_tenants_plan_id'), 'tenants', ['plan_id'], unique=False)
    op.create_foreign_key(None, 'tenants', 'subscription_plans', ['plan_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tenants', type_='foreignkey')
    op.drop_index(op.f('ix_tenants_plan_id'), table_name='tenants')
    op.drop_column('tenants', 'plan_id')
    # ### end Alembic commands ###
