"""Add description to Module

Revision ID: 7509b731faa3
Revises: b6b9fe914a38
Create Date: 2026-05-06 02:32:03.261609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7509b731faa3'
down_revision: Union[str, Sequence[str], None] = 'b6b9fe914a38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modules', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('modules', 'description')
    # ### end Alembic commands ###
