"""Arquitectura SaaS

Revision ID: 8426775232b3
Revises: a1b2c3d4e5f6
Create Date: 2026-04-07 04:32:55.890968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8426775232b3'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('module_id', sa.Uuid(), nullable=False),
    sa.Column('stripe_subscription_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_subscriptions_module_id'), 'subscriptions', ['module_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_stripe_subscription_id'), 'subscriptions', ['stripe_subscription_id'], unique=True)
    op.create_index(op.f('ix_subscriptions_tenant_id'), 'subscriptions', ['tenant_id'], unique=False)
    op.create_table('role_module_access',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('module_id', sa.Uuid(), nullable=False),
    sa.Column('can_read', sa.Boolean(), nullable=False),
    sa.Column('can_write', sa.Boolean(), nullable=False),
    sa.Column('can_delete', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'module_id', name='uq_role_module')
    )
    op.create_index(op.f('ix_role_module_access_id'), 'role_module_access', ['id'], unique=False)
    op.create_index(op.f('ix_role_module_access_module_id'), 'role_module_access', ['module_id'], unique=False)
    op.create_index(op.f('ix_role_module_access_role_id'), 'role_module_access', ['role_id'], unique=False)
    op.create_table('tenant_members',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'tenant_id', name='uq_user_tenant_membership')
    )
    op.create_index(op.f('ix_tenant_members_id'), 'tenant_members', ['id'], unique=False)
    op.create_index(op.f('ix_tenant_members_role_id'), 'tenant_members', ['role_id'], unique=False)
    op.create_index(op.f('ix_tenant_members_tenant_id'), 'tenant_members', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_tenant_members_user_id'), 'tenant_members', ['user_id'], unique=False)
    op.drop_table('tenant_modules')
    op.add_column('modules', sa.Column('is_premium', sa.Boolean(), nullable=False))
    op.alter_column('modules', 'code',
               existing_type=sa.VARCHAR(length=50),
               type_=sqlmodel.sql.sqltypes.AutoString(length=100),
               existing_nullable=False)
    op.alter_column('modules', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sqlmodel.sql.sqltypes.AutoString(length=255),
               existing_nullable=False)
    op.drop_index(op.f('ix_modules_name'), table_name='modules')
    op.create_foreign_key(None, 'modules', 'users', ['created_by'], ['id'])
    op.drop_column('modules', 'device_info')
    op.drop_column('modules', 'last_ip')
    op.drop_column('modules', 'description')
    op.add_column('roles', sa.Column('is_custom', sa.Boolean(), nullable=False))
    op.alter_column('roles', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('roles', 'name',
               existing_type=sa.VARCHAR(length=80),
               type_=sqlmodel.sql.sqltypes.AutoString(length=100),
               existing_nullable=False)
    op.drop_index(op.f('ix_roles_code'), table_name='roles')
    op.drop_constraint(op.f('roles_tenant_id_fkey'), 'roles', type_='foreignkey')
    op.create_foreign_key(None, 'roles', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'roles', 'tenants', ['tenant_id'], ['id'])
    op.drop_column('roles', 'device_info')
    op.drop_column('roles', 'last_ip')
    op.drop_column('roles', 'code')
    op.add_column('tenants', sa.Column('stripe_customer_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('tenants', sa.Column('billing_status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False))
    op.add_column('tenants', sa.Column('trial_ends_at', sa.DateTime(), nullable=True))
    op.add_column('tenants', sa.Column('current_period_end', sa.DateTime(), nullable=True))
    op.alter_column('tenants', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sqlmodel.sql.sqltypes.AutoString(length=255),
               existing_nullable=False)
    op.create_index(op.f('ix_tenants_stripe_customer_id'), 'tenants', ['stripe_customer_id'], unique=True)
    op.create_foreign_key(None, 'tenants', 'users', ['created_by'], ['id'])
    op.drop_column('tenants', 'device_info')
    op.drop_column('tenants', 'last_ip')
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_constraint(op.f('fk_users_role_id'), 'users', type_='foreignkey')
    op.drop_constraint(op.f('users_tenant_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'users', ['created_by'], ['id'])
    op.drop_column('users', 'role_id')
    op.drop_column('users', 'is_tenant_admin')
    op.drop_column('users', 'device_info')
    op.drop_column('users', 'tenant_id')
    op.drop_column('users', 'last_ip')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_ip', sa.VARCHAR(length=45), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('device_info', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('is_tenant_admin', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('role_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_tenant_id_fkey'), 'users', 'tenants', ['tenant_id'], ['id'])
    op.create_foreign_key(op.f('fk_users_role_id'), 'users', 'roles', ['role_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.add_column('tenants', sa.Column('last_ip', sa.VARCHAR(length=45), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('device_info', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tenants', type_='foreignkey')
    op.drop_index(op.f('ix_tenants_stripe_customer_id'), table_name='tenants')
    op.alter_column('tenants', 'name',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('tenants', 'current_period_end')
    op.drop_column('tenants', 'trial_ends_at')
    op.drop_column('tenants', 'billing_status')
    op.drop_column('tenants', 'stripe_customer_id')
    op.add_column('roles', sa.Column('code', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('roles', sa.Column('last_ip', sa.VARCHAR(length=45), autoincrement=False, nullable=True))
    op.add_column('roles', sa.Column('device_info', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'roles', type_='foreignkey')
    op.drop_constraint(None, 'roles', type_='foreignkey')
    op.create_foreign_key(op.f('roles_tenant_id_fkey'), 'roles', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_roles_code'), 'roles', ['code'], unique=False)
    op.alter_column('roles', 'name',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=100),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
    op.alter_column('roles', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('roles', 'is_custom')
    op.add_column('modules', sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('modules', sa.Column('last_ip', sa.VARCHAR(length=45), autoincrement=False, nullable=True))
    op.add_column('modules', sa.Column('device_info', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'modules', type_='foreignkey')
    op.create_index(op.f('ix_modules_name'), 'modules', ['name'], unique=False)
    op.alter_column('modules', 'name',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('modules', 'code',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('modules', 'is_premium')
    op.create_table('tenant_modules',
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('module_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], name=op.f('tenant_modules_module_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('tenant_modules_tenant_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tenant_id', 'module_id', name=op.f('tenant_modules_pkey'))
    )
    op.drop_index(op.f('ix_tenant_members_user_id'), table_name='tenant_members')
    op.drop_index(op.f('ix_tenant_members_tenant_id'), table_name='tenant_members')
    op.drop_index(op.f('ix_tenant_members_role_id'), table_name='tenant_members')
    op.drop_index(op.f('ix_tenant_members_id'), table_name='tenant_members')
    op.drop_table('tenant_members')
    op.drop_index(op.f('ix_role_module_access_role_id'), table_name='role_module_access')
    op.drop_index(op.f('ix_role_module_access_module_id'), table_name='role_module_access')
    op.drop_index(op.f('ix_role_module_access_id'), table_name='role_module_access')
    op.drop_table('role_module_access')
    op.drop_index(op.f('ix_subscriptions_tenant_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_stripe_subscription_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_module_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_audit_logs_tenant_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
