"""bakers_percent_and_unit_cost_override

Revision ID: 99edafcf2e08
Revises: f7b8c9d0e1f2
Create Date: 2026-05-19 02:24:44.998120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '99edafcf2e08'
down_revision: Union[str, Sequence[str], None] = 'f7b8c9d0e1f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_price_history', sa.Column('created_by', sa.Uuid(), nullable=True))
    op.alter_column('inventory_price_history', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('inventory_price_history', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_foreign_key(None, 'inventory_price_history', 'users', ['created_by'], ['id'])
    op.add_column('recipe_ingredients', sa.Column('bakers_percent', sa.Numeric(precision=10, scale=4), nullable=False, server_default='100.0000'))
    op.add_column('recipe_ingredients', sa.Column('unit_cost_override', sa.Numeric(precision=10, scale=4), nullable=True))
    op.drop_column('recipe_ingredients', 'quantity')
    # Quitar el server_default una vez populadas las filas existentes
    op.alter_column('recipe_ingredients', 'bakers_percent', server_default=None)
    op.add_column('recipes', sa.Column('panes_por_libra_harina', sa.Integer(), nullable=True))
    op.add_column('stock_movements', sa.Column('created_by', sa.Uuid(), nullable=True))
    op.alter_column('stock_movements', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('stock_movements', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_foreign_key(None, 'stock_movements', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stock_movements', type_='foreignkey')
    op.alter_column('stock_movements', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('stock_movements', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('stock_movements', 'created_by')
    op.alter_column('recipes', 'instructions',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('recipes', 'panes_por_libra_harina')
    op.add_column('recipe_ingredients', sa.Column('quantity', sa.DOUBLE_PRECISION(precision=53), nullable=False, server_default='1.0'))
    op.drop_column('recipe_ingredients', 'unit_cost_override')
    op.drop_column('recipe_ingredients', 'bakers_percent')
    op.drop_constraint(None, 'inventory_price_history', type_='foreignkey')
    op.alter_column('inventory_price_history', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('inventory_price_history', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('inventory_price_history', 'created_by')
    # ### end Alembic commands ###
