"""rbac_to_modules

Revision ID: a1d310dc68bb
Revises: b8e6a1577b80
Create Date: 2026-05-07 01:24:45.185892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'a1d310dc68bb'
down_revision: Union[str, Sequence[str], None] = 'b8e6a1577b80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_member_module_access',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_member_id', sa.Uuid(), nullable=False),
    sa.Column('module_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.ForeignKeyConstraint(['tenant_member_id'], ['tenant_members.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_member_id', 'module_id', name='uq_tenant_member_module')
    )
    op.create_index(op.f('ix_tenant_member_module_access_id'), 'tenant_member_module_access', ['id'], unique=False)
    op.create_index(op.f('ix_tenant_member_module_access_module_id'), 'tenant_member_module_access', ['module_id'], unique=False)
    op.create_index(op.f('ix_tenant_member_module_access_tenant_member_id'), 'tenant_member_module_access', ['tenant_member_id'], unique=False)
    op.drop_index(op.f('ix_role_module_access_id'), table_name='role_module_access')
    op.drop_index(op.f('ix_role_module_access_module_id'), table_name='role_module_access')
    op.drop_index(op.f('ix_role_module_access_role_id'), table_name='role_module_access')
    op.drop_table('role_module_access')
    op.add_column('invitations', sa.Column('member_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.drop_index(op.f('ix_invitations_role_id'), table_name='invitations')
    op.drop_constraint('invitations_role_id_fkey', 'invitations', type_='foreignkey')
    op.drop_column('invitations', 'role_id')
    op.add_column('tenant_members', sa.Column('member_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.drop_index(op.f('ix_tenant_members_role_id'), table_name='tenant_members')
    op.create_index(op.f('ix_tenant_members_member_type'), 'tenant_members', ['member_type'], unique=False)
    op.drop_constraint('tenant_members_role_id_fkey', 'tenant_members', type_='foreignkey')
    op.drop_column('tenant_members', 'role_id')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_tenant_id'), table_name='roles')
    op.drop_table('roles')
    
    # Backfill para no dejar nulls y luego requerirlo
    op.execute("UPDATE invitations SET member_type='employee' WHERE member_type IS NULL")
    op.execute("UPDATE tenant_members SET member_type='employee' WHERE member_type IS NULL")
    op.alter_column('invitations', 'member_type', nullable=False)
    op.alter_column('tenant_members', 'member_type', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant_members', sa.Column('role_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('tenant_members_role_id_fkey'), 'tenant_members', 'roles', ['role_id'], ['id'])
    op.drop_index(op.f('ix_tenant_members_member_type'), table_name='tenant_members')
    op.create_index(op.f('ix_tenant_members_role_id'), 'tenant_members', ['role_id'], unique=False)
    op.drop_column('tenant_members', 'member_type')
    op.add_column('invitations', sa.Column('role_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('invitations_role_id_fkey'), 'invitations', 'roles', ['role_id'], ['id'])
    op.create_index(op.f('ix_invitations_role_id'), 'invitations', ['role_id'], unique=False)
    op.drop_column('invitations', 'member_type')
    op.create_table('roles',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('is_custom', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('roles_created_by_fkey')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('roles_tenant_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('roles_pkey'))
    )
    op.create_index(op.f('ix_roles_tenant_id'), 'roles', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=False)
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_table('role_module_access',
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('role_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('module_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('can_read', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('can_write', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('can_delete', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('role_module_access_created_by_fkey')),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], name=op.f('role_module_access_module_id_fkey')),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('role_module_access_role_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('role_module_access_pkey')),
    sa.UniqueConstraint('role_id', 'module_id', name=op.f('uq_role_module'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_role_module_access_role_id'), 'role_module_access', ['role_id'], unique=False)
    op.create_index(op.f('ix_role_module_access_module_id'), 'role_module_access', ['module_id'], unique=False)
    op.create_index(op.f('ix_role_module_access_id'), 'role_module_access', ['id'], unique=False)
    op.drop_index(op.f('ix_tenant_member_module_access_tenant_member_id'), table_name='tenant_member_module_access')
    op.drop_index(op.f('ix_tenant_member_module_access_module_id'), table_name='tenant_member_module_access')
    op.drop_index(op.f('ix_tenant_member_module_access_id'), table_name='tenant_member_module_access')
    op.drop_table('tenant_member_module_access')
    # ### end Alembic commands ###
