"""onboarding_invitations_v2

Revision ID: b6b9fe914a38
Revises: 34715560e1ea
Create Date: 2026-05-05 03:12:38.445204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b6b9fe914a38'
down_revision: Union[str, Sequence[str], None] = '34715560e1ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_config',
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    # Add status column with server_default for existing rows, then migrate data
    op.add_column('invitations', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False, server_default='pending'))
    op.create_index(op.f('ix_invitations_status'), 'invitations', ['status'], unique=False)
    # Migrate existing data: is_accepted=True → status='accepted'
    op.execute("UPDATE invitations SET status = 'accepted' WHERE is_accepted = TRUE")
    op.drop_column('invitations', 'is_accepted')
    # Add onboarding_completed with server_default=True for existing users (they're already in the system)
    op.add_column('users', sa.Column('onboarding_completed', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'onboarding_completed')
    op.add_column('invitations', sa.Column('is_accepted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_invitations_status'), table_name='invitations')
    op.drop_column('invitations', 'status')
    op.drop_table('platform_config')
    # ### end Alembic commands ###
