"""Add frontend_route to Module

Revision ID: b8e6a1577b80
Revises: 7509b731faa3
Create Date: 2026-05-06 03:03:13.269929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b8e6a1577b80'
down_revision: Union[str, Sequence[str], None] = '7509b731faa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modules', sa.Column('frontend_route', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('modules', 'frontend_route')
    # ### end Alembic commands ###
