"""Add logo and theme to Tenant

Revision ID: e4fa0d8d6a2f
Revises: 04683d9beeee
Create Date: 2026-05-07 12:58:55.231571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e4fa0d8d6a2f'
down_revision: Union[str, Sequence[str], None] = '04683d9beeee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('logo_url', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True))
    op.add_column('tenants', sa.Column('theme_color', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'theme_color')
    op.drop_column('tenants', 'logo_url')
    # ### end Alembic commands ###
