"""Creacion tablas Tenant y User

Revision ID: f8a82cf34560
Revises: 4c135d16186f
Create Date: 2026-03-08 17:20:13.999967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'f8a82cf34560'
down_revision: Union[str, Sequence[str], None] = '4c135d16186f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Se agrega server_default=sa.text('now()') a las columnas DateTime no nulas
    op.add_column('tenants', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
    
    op.add_column('tenants', sa.Column('created_by', sa.Uuid(), nullable=True))
    op.add_column('tenants', sa.Column('last_ip', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=True))
    op.add_column('tenants', sa.Column('device_info', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    
    # Se agrega server_default=sa.text('now()') a las columnas DateTime no nulas
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
    
    op.add_column('users', sa.Column('created_by', sa.Uuid(), nullable=True))
    op.add_column('users', sa.Column('last_ip', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=True))
    op.add_column('users', sa.Column('device_info', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'device_info')
    op.drop_column('users', 'last_ip')
    op.drop_column('users', 'created_by')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('tenants', 'device_info')
    op.drop_column('tenants', 'last_ip')
    op.drop_column('tenants', 'created_by')
    op.drop_column('tenants', 'updated_at')
    # ### end Alembic commands ###
